### ISSUE TITLE
IAM-based client authentication

### ISSUE THREAD

**Issue by hcourse-nydig** [cloudposse/terraform-aws-msk-apache-kafka-cluster#20]
## Describe the Feature

AWS have released IAM-based [SASL security for MSK](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html#create-iam-access-control-cluster-in-console). It'd be great if we could configure support for this via the Cloudposse module.

## Expected Behavior

Users should be able to specify IAM-based SASL security for clients as an alternative to SASL-SCRAM.

## Use Case

We're currently looking at deploying an MSK cluster and would like the ability to configure client access via IAM instead of via SCRAM credentials in Secrets Manager.

## Describe Ideal Solution

An option in the Cloudposse module to enable IAM-based SASL security that calls `CreateCluster` with the correct SASL options to enable IAM-based security.

## Alternatives Considered

SASL-SCRAM is an existing client auth option but there's currently no way to update a SCRAM cluster to use IAM-based client security. IAM-based client security would add value for users that have a unified IAM-based security architecture.

## Additional Context

Happy to raise a PR for this although I am (like everyone) tight for time and not a tf expert.

**Comment by osterman** [comment]
Thanks for opening the issue. Feature request makes sense. We probably won't get to this anytime soon, but we can promptly review any PRs if you ping us in #pr-reviews in our public slack team.

**Comment by hcourse-nydig** [comment]
Done some digging into this, looks like we're blocked on support in the aws provider for the time being. [Lots of interest on the issue in the tf repo](https://github.com/hashicorp/terraform-provider-aws/issues/19295) though so expect this to be sorted fairly fast.
