### ISSUE TITLE
Module "kafka" (from resource.tf:12) cannot be found in the module registry at registry.terraform.io.

### ISSUE THREAD

**Issue by Yuvaraj-Natarajan** [cloudposse/terraform-aws-msk-apache-kafka-cluster#37]
Team,
looks like source for module kafka is not working (source = "cloudposse/apache-kafka-cluster/aws")
![image](https://user-images.githubusercontent.com/58209227/138236072-b5518a32-4d5e-40bd-a0f4-a92523a8cdcd.png)
was getting error - Module "kafka" (from resource.tf:12) cannot be found in the module registry at registry.terraform.io.

so i changed the source = "cloudposse/msk-apache-kafka-cluster/aws" its started working. Requesting you to take look & if its valid kindly update Git.

**Comment by nitrocode** [comment]
We just updated the docs for this.

Try this.

```hcl
module "kafka" {
  source = "cloudposse/msk-apache-kafka-cluster/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "x.x.x"
}
```
