### ISSUE TITLE
Enabling IAM and SCRAM authentication at the same time fails

### ISSUE THREAD

**Issue by rodrigorfk** [cloudposse/terraform-aws-msk-apache-kafka-cluster#42]
## Describe the Bug
When enabling both `client_sasl_iam_enabled` and `client_sasl_scram_enabled` an `Error: Too many sasl blocks` is being produced.

## Expected Behavior
Having multiple authentication is supported by AWS MSK and also by the AWS Provider, however the terraform-aws-msk-apache-kafka-cluster module is not working when enabling multiple SASL authentication at the same time.

## Steps to Reproduce
1. Create a simple module consuming the terraform-aws-msk-apache-kafka-cluster module and set  `client_sasl_iam_enabled` and `client_sasl_scram_enabled` to `true`, proper providing an AWS SecretManager Secret ARN on the `client_sasl_scram_secret_association_arns` variable.
2. Run `terraform init`
3. Run `terraform plan`
4. The mentioned `Error: Too many sasl blocks` is going to be produced.

## Screenshots
![image](https://user-images.githubusercontent.com/1995033/138826808-bb4a38b1-e8eb-45c8-a51c-9eb85c49b156.png)

## Environment (please complete the following information):
 - OS: OSX
 - Module Version: 0.7.3
 - Terraform Version: 1.0.2
 - AWS Provider Version: 3.63.0

**Comment by mlongarai** [comment]
Hey Guys, I am still facing this error in the latest version of the module. Could this be happening because the MSK cluster is already running? 

I would appreciate any help in this matter. Cheers!
