### ISSUE TITLE
Please update the module to use the latest cloudposse / terraform-aws-security-group tag

### ISSUE THREAD

**Issue by adrianmiron** [cloudposse/terraform-aws-msk-apache-kafka-cluster#72]
Hello,

When trying to expand the `allowed_cidr_blocks` variable with another CIDR i get the bellow error : 

`Error: [WARN] A duplicate Security Group rule was found on (sg-0da51b4f2466544ea). This may be
│ a side effect of a now-fixed Terraform issue causing two security groups with
│ identical attributes but different source_security_group_ids to overwrite each
│ other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
│ information and instructions for recovery. Error: InvalidPermission.Duplicate: the specified rule "peer: 172.25.0.0/16, TCP, from port: 9094, to port: 9094, ALLOW" already exists
│ 	status code: 400, request id: c0f3cfd9-7fe6-4e78-8fdf-08cc751d93f2
│
│   with module.kafka.module.msk_cluster.module.broker_security_group.aws_security_group_rule.keyed["_m[0]#tls#cidr"],
│   on .terraform/modules/kafka.msk_cluster.broker_security_group/main.tf line 141, in resource "aws_security_group_rule" "keyed":
│  141: resource "aws_security_group_rule" "keyed" {`

The only way to move forward atm  is to go into the submodule through the `.terraform` folder and remove the lifecycle blocks  for the 1.0.1 version : 

` lifecycle {
    create_before_destroy = true
  }`

Please bump the MSK module to use the latest version of the SG module.

Thanks,
Adrian

**Comment by Nuru** [comment]
Closed by #85
